### ISSUE TITLE
problems liking and thumbing up notes

### ISSUE THREAD

**Issue by GretaFrank** [hzrd149/nostrudel#25]
here is what i get:

![image](https://github.com/hzrd149/nostrudel/assets/146442815/3a18999a-79d3-42e2-a80c-36768828b2ef)

first of all you can see the note was thumbed up and thumbed down twice each - the problem is i put all four of those thumbs there and did so at the same time - ideally this shouldn't be possible IMO.  i should be able to thumb EITHER up OR down, but not both.  and not more than once.

the other issue is i can't find the HEART icon for "like" ... perhaps it's that vertical rectangle that isn't getting rendered properly ?  it always shows as rectangle for me.  i never seen a heart there.  and if i press it - it posts an identical looking rectangle next to the thumbs.

i am on Chrome in Windows 10.

**Comment by GretaFrank** [comment]
update: some posts have a red heart i can click on and it increases the heart count.  

but most post do not anything that can be "liked" ...

**Comment by hzrd149** [comment]
posts will show all the reactions of other users on them, so that might explain why some posts have a red heart and others dont.

Right now there isn't a good way to add your own custom reactions ( like, dislike, heart, etc... ) to posts. noStrudel supports custom emoji packs for reactions ( you can find them here https://nostrudel.ninja/#/emojis/browse ) but its missing the option to react with a Unicode emoji

Its on my to-do list though :smile:

**Comment by GretaFrank** [comment]
Ok thank you @hzrd149 

it now looks like this:

![image](https://github.com/hzrd149/nostrudel/assets/146442815/09bcfb7b-1730-413f-89b5-d58f000c6d2a)

and i can finally "heart" notes !

thanks again !

**Comment by hzrd149** [comment]
No problem, thanks for creating the issue. I would have forgotten about the feature if not for this issue
