### ISSUE TITLE
feature request - open clicked notes in new tab by default

### ISSUE THREAD

**Issue by GretaFrank** [hzrd149/nostrudel#54]
if i right click on a note in my timeline and open in new tab it's perfect - i read the discussion, close it and i'm back to where i was

but if i left click on it everything gets screwed up and i lose the place in timeline

why not just open it in new tab by default ?  it isn't hard to close a tab.

really all these "solutions" like different panels that open are searching for a problem ( other clients do it too ) because the TAB functionality of browsers already solved it all 

IMO that is

you may disagree

**Comment by hzrd149** [comment]
I also like using tabs, which is why I made all the notes normal links so you can right click on them. also if you have a mouse with a middle button you can use it to open any link (note) in a new tab.

Although opening every note in either the drawer or a new tab would only be a band-aid on the root issue which is the timeline not restoring your position.
I've got an idea on how to fix this issue, but its not at the top of my todo list right now :(
